### ISSUE TITLE
Which  function is blocking  and which  function is non-blocking?

### ISSUE THREAD

**Issue by ygm521** [thibaultcha/lua-resty-socket#16]
hello，
 I know that cosocket is non-blocking and some stages cannot be used.
 I know that luasocket is blocked. 
Which  function is blocking  and which  function is non-blocking of Your library?  thanks！

**Comment by thibaultcha** [comment]
Hello,

Sorry for the delay, I missed this issue. The goal of this project is to always deliver a non-blocking socket, unless your application is in a phase that does _not_ support non-blocking sockets (e.g. `init`, `timer`...). If you request a socket in those phases, you will get a warning log (https://github.com/thibaultcha/lua-resty-socket/blob/master/lib/resty/socket.lua#L159) and you can assume the socket will be blocking. That does not matter in the `init` phase, which is the primary use-case for this library (fallback to LuaSocket in the `init` phase so that libraries you are using that call `ngx.socket.tcp()` do not need to be updated to support LuaSocket fallback themselves).
