### ISSUE TITLE
Lua-Resty-Redis-Cluster: ERR Protocol error: invalid bulk length 

### ISSUE THREAD

**Issue by satishnaidu** [thibaultcha/lua-resty-socket#17]
Hi @thibaultcha , 

nginx version: openresty/1.15.8.2
built by gcc 9.3.0 (Ubuntu 9.3.0-10ubuntu2)
built with OpenSSL 1.1.0k  28 May 2019

lua-resty-core: 0.1.18
OS: Linux ea01851460a5 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

In order to implement rate-limiting, I have to use Redis-cluster in the body_by_lua_block phase.

I have changed the following Redis library file locally to use lua-resty-socket instead of ngx.socket.tcp

https://github.com/openresty/lua-resty-redis/blob/master/lib/resty/redis.lua#L8
https://github.com/iresty/lua-resty-redis-cluster/blob/devel/lib/rediscluster.lua#L2

I'm getting the following error in the logs, so not able to increment the Redis counter.

    2020/06/08 22:47:24 [error] 7#7: *9 [lua] resty-rediscluster.lua:162: fetch_slots(): failed to fetch slots: ERR Protocol error: invalid bulk length while sending to client, 

Please let me know, how to proceed with this, thanks.

**Comment by thibaultcha** [comment]
Hi,

This error isn't reported by this library, but by lua-resty-redis-cluster (see https://github.com/iresty/lua-resty-redis-cluster/blob/devel/lib/rediscluster.lua#L162). Most likely, your code isn't using the library properly. In any case, this has nothing to do with this library.

Also, you should not use this library in phases like `body_filter_by_lua` or `header_filter_by_lua`, since the underlying luasocket implementation will block the NGINX event pool which will result in incredibly low performance (most likely unusable in production). You must find another way.
